import { initBurger } from './burger.js';
import { initI18n } from './i18n.js';
import { initLoader } from './loader.js';
import { initCookies } from './cookies.js';
import { initCursor } from './cursor.js';
import { initLoadMore } from './loadMore.js';
import { initTheme } from './theme.js';
import { initActiveNavOnScroll } from './active-nav.js';
import { initProjectAccordion } from './projects-accordion.js';
import { initReveal } from './reveal.js';

initI18n();
initBurger();
initLoader();
initCookies();
initCursor();
initLoadMore();
initTheme();
initActiveNavOnScroll();
initProjectAccordion();
initReveal();